BlocommerceApplication:
  component: "@sls-next/serverless-component"
  inputs:
    bucketName: ${env.DEPLOYMENT_BUCKET}
    cloudfront:
      # if you want to use an existing cloudfront distribution, provide it here
      distributionId: ${env.CF_DIST_ID}
      # error page settings
      errorPages:
        - code: 403
          path: "/index.html"
          minTTL: 5 # optional, minimum ttl the error is cached (default 10)
          responseCode: 403 # optional, alters the response code
    memory:
      defaultLambda: 2048
      apiLambda: 3072
      imageLambda: 1024